---
name: Pyramid Pile
description: Default shapez Template
game: shapez
requires:
  version: 0.6.3
shapez:
  progression_balancing:
    random: 20
    random-low: 20
    random-high: 20
    disabled: 20
    normal: 20
    extreme: 20
  accessibility:
    full: 50
    minimal: 50
  goal:
    vanilla: 50
    mam: 50
    even_fasterer: 50
    efficiency_iii: 50
  goal_amount:
    random: 0
    random-low: 0
    random-high: 0
    random-range-27-50: 50
    minimum_mam: 0
    recommended_mam: 0
    long_game_mam: 0
    minimum_even_fasterer: 0
    recommended_even_fasterer: 0
    long_play_even_fasterer: 0
  required_shapes_multiplier:
    "10": 50
    random: 0
    random-low: 50
    random-high: 0
  allow_floating_layers:
    "false": 50
    "true": 50
  randomize_level_requirements:
    "false": 50
    "true": 50
  randomize_upgrade_requirements:
    "false": 50
    "true": 50
  randomize_level_logic:
    vanilla: 20
    vanilla_shuffled: 20
    stretched: 20
    stretched_shuffled: 20
    quick: 20
    quick_shuffled: 20
    random_steps: 20
    random_steps_shuffled: 20
    hardcore: 20
    dopamine: 20
    dopamine_overflow: 20
  randomize_upgrade_logic:
    vanilla_like: 20
    linear: 20
    category: 20
    category_random: 20
    hardcore: 0
  throughput_levels_ratio:
    random: 20
    random-low: 20
    random-high: 20
    vanilla: 20
    only_total: 20
    half_half: 20
    only_throughput: 20
  complexity_growth_gradient:
    "0.5": 20
    random: 20
    random-low: 20
    random-high: 20
  same_late_upgrade_requirements:
    "false": 50
    "true": 50
  early_balancer_tunnel_and_trash:
    none: 20
    5_buildings: 20
    3_buildings: 20
    sphere_1: 20
  lock_belt_and_extractor:
    "false": 50
    "true": 50
  include_achievements:
    "false": 50
    "true": 50
  exclude_softlock_achievements:
    "false": 0
    "true": 50
  exclude_long_playtime_achievements:
    "false": 0
    "true": 50
  exclude_progression_unreasonable:
    "false": 0
    "true": 50
  shapesanity_amount:
    "50": 20
    random: 20
    random-low: 20
    random-high: 20
  traps_percentage:
    random: 20
    random-low: 20
    random-high: 20
    none: 20
    rare: 20
    occasionally: 20
    maximum_suffering: 20
  include_whacky_upgrades:
    "false": 50
    "true": 50
  split_inventory_draining_trap:
    "false": 50
    "true": 50
  toolbar_shuffling:
    "false": 50
    "true": 50
  local_items: []
  non_local_items: []
  start_inventory: {}
  start_hints: []
  start_location_hints: []
  exclude_locations: []
  priority_locations: []
  item_links: []
  plando_items: []
triggers:
  - option_category: shapez
    option_name: goal
    option_result: even_fasterer
    options:
      shapez:
        goal_amount: random-range-16-35
